##
# Configuration settings for use by the Rails application
# Made available via the SimpleConfig global class
# Use for settings such as mail server configurations, Amazon keys and secrets etc...
# You can use ERB too
#
# NNB: This file contains SECRETS! NOT FOR SOURCE CONTROL!!!
#
##

##
# Define shared settings
#
shared: &shared

  # Amazon
  s3_key: <%= ENV['S3_KEY'] %>
  s3_secret: <%= ENV['S3_SECRET'] %>

  # reCAPTCHA
  recaptcha_key: <%= ENV['RECAPTCHA_PUBLIC_KEY'] %>
  recaptcha_secret: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>

  # SMTP server authentication
  smtp_user_name: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>

  # encryption key for S3 files
  hash_secret: <%= ENV['S3_HASH'] %>

##
# Define settings per Rails environment, 
# provide overrides to the shared settings as needed
#
development:
  # inherit shared settings
  <<: *shared

  # reCAPTCHA (0.0.0.0)
  recaptcha_key: <%= ENV['RECAPTCHA_PUBLIC_KEY_DEV'] %>
  recaptcha_secret: <%= ENV['RECAPTCHA_PRIVATE_KEY_DEV'] %>

test:
  # inherit shared settings
  <<: *shared

production:
  # inherit shared settings
  <<: *shared
